# Generated by Django 6.1 on 2026-08-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='test',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Masalan 1 soat uchun 1, 30 daqiqa uchun 0.5 kiriting.', max_digits=4, verbose_name='Vaqt (soat)'),
        ),
    ]
